language: node_js
node_js:
  - 14
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - "npm i -g gatsby"
  - "yarn"
script:
  - "yarn build"
after_success:
  - "yarn deploy:github"
